site_name: Audition ToolkitğŸ¼ğŸ¹
site_url: https://demo.com

nav:
  - Home(AT)ğŸ™ : index.md
  - Advanced edit ğŸµğŸ“ŠğŸšï¸: equalizer.md
  - Trim & Split âœ‚ï¸ã€°ï¸âœ‚ï¸ : trimSplit.md
  - Voice changer & Reverse ğŸ—£ï¸ğŸ™ï¸ â—€ï¸: voiceReverse.md
  - Karaoke Extractor ğŸ—£ï¸ğŸš«ğŸ¶ : karaoke.md
  - Magic Enhancer ğŸ™ï¸ğŸšï¸ğŸ”Š: enhancer.md


theme:
    name: material
